<?php

/**
* @file
* Remove Duplicate Nodes.
*/

/**
* Delete duplicates from selected content type, based on title. By Robert Douglass.
* @see <a href="http://robshouse.net/blog-post/remove-duplicate-nodes-dedupe-based-title
" title="http://robshouse.net/blog-post/remove-duplicate-nodes-dedupe-based-title
" rel="nofollow">http://robshouse.net/blog-post/remove-duplicate-nodes-dedupe-based-title
</a> */
function nodededupe_cron() {

$result = db_query("SELECT n.nid AS nid, n.uid AS uid, n.status AS status,
      n.title AS title
      FROM node n
      LEFT JOIN field_data_field_dato ON n.nid = field_data_field_dato.entity_id AND field_data_field_dato.entity_type = 'node'
      INNER JOIN users u ON n.uid = u.uid
      INNER JOIN (
         SELECT entity_id, n.title AS title, n.nid AS nid,
         COUNT( * ) AS duplicate
		 FROM field_data_field_dato, node n
         WHERE (
          n.type = 'events' AND (n.nid = field_data_field_dato.entity_id) AND n.status = 1
        )
        GROUP BY title, field_dato_value
        HAVING count( duplicate ) > 1
        ) nn ON n.title = nn.title
		WHERE (
(n.uid = '101')
		)
      ORDER BY title ASC", array());

foreach ($result as $row) {
node_delete($row->nid);
drupal_set_message("Deleted node nid={$row->nid}, title={$row->title}");
}
cache_clear_all('*', 'cache_page', TRUE);
}
